# Generated by Django 4.0 on 2022-08-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('start', models.DateField(blank=True)),
                ('current', models.BooleanField(default=False)),
                ('end', models.DateField(blank=True)),
                ('achievements', models.TextField(blank=True)),
            ],
        ),
    ]
