# Generated by Django 4.0 on 2022-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_position_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='start',
            field=models.DateField(),
        ),
    ]
