# Generated by Django 4.0 on 2022-08-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_position_end_alter_position_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('average', models.FloatField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('start', models.DateField(blank=True, null=True)),
                ('end_or_estimated', models.DateField(blank=True, null=True)),
                ('average', models.FloatField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
