# Generated by Django 4.0 on 2022-08-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_course_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='average',
        ),
    ]
