# Generated by Django 4.0 on 2022-08-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_remove_course_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
