# Generated by Django 4.0 on 2022-08-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_course_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.URLField(blank=True),
        ),
    ]
