# Generated by Django 4.0 on 2022-08-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_course_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
