# Generated by Django 4.0 on 2022-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_course_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
