# Generated by Django 4.0 on 2022-08-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
